name: Run Python Tests

on: push

permissions:
  contents: read

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install apt prerequisites
      run: sudo apt-get install -y graphviz graphviz-dev
    - name: "Setup Python, Poetry and Dependencies"
      uses: packetcoders/action-setup-cache-python-poetry@main
      with:
        python-version: 3.11
        poetry-version: 1.2.2
    - name: Run Python tests
      run: poetry run pytest -vv
